### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by I2F-Yui-Hatano** [YoungerDryas89/JAVMovieScraper#1]
Is it possible to create a JAR for 0.4.0 like JAVMovieScraper-v0.3.7.jar ?

**Comment by YoungerDryas89** [comment]
> Is it possible to create a JAR for 0.4.0 like JAVMovieScraper-v0.3.7.jar ?

Hi, I just released a new version with JAR included. Sorry I couldn't get to you faster

**Comment by I2F-Yui-Hatano** [comment]
Thank you so much !
