### ISSUE TITLE
Windows 11 - "A Java Exception has occurred." ERROR when launching it.

### ISSUE THREAD

**Issue by clevnumb** [YoungerDryas89/JAVMovieScraper#2]
**Describe the bug**
Exception when launching it.

I have the old 0.37 version is working fine...the latest Java is installed and up to date.  I'm on Windows 11

**Give an example**
![image](https://github.com/user-attachments/assets/6d759e07-af0f-4a83-bca5-8c9fe5338d78)

Ideas?

**Comment by YoungerDryas89** [comment]
If you're running 0.3.7 then I would download the most recent version, else try to run it through the PowerShell and post what you see here.

**Comment by clevnumb** [comment]
> If you're running 0.3.7 then I would download the most recent version, else try to run it through the PowerShell and post what you see here.

Hello,

0.3.7 is the latest (of the original build) here: https://github.com/DoctorD1501/JAVMovieScraper/releases/tag/v0.3.7

I'm trying to run the latest here JAVMovieScraper-0.6.0.jar

Same error in PowerShell: 

![image](https://github.com/user-attachments/assets/a5e439ba-53d3-4d17-b6e3-fd95ee5262d4)

**Comment by YoungerDryas89** [comment]
I just released a new build, could you try that? Also what version of java are you using?

**Comment by clevnumb** [comment]
Version 8 Update 421 (latest)

I will try that, thank you.

**Comment by Yirenxs** [comment]
The same issue. Using jre-8u421-windows-x64.exe & JAVMovieScraper-0.6.1.jar

**Comment by YoungerDryas89** [comment]
It's technically true you're using the latest Java, but it's the latest Java 8. Also I forgot to update the description that it's built with Java 21. Give it a go: https://www.oracle.com/java/technologies/downloads/#jdk22-windows

**Comment by clevnumb** [comment]
That worked, thanks!
